:memo: プライバシーポリシー及び利用規約の雛形を追加
muchoco-dev/docs pull request #1
Opened 2023-10-14 08:31 UTC by kuniyuki-f

# 対応したこと/対応しないこと
- 以下のリンク先にあるプライバシーポリシー、利用規約の内容をマークダウンで作成した
  - https://kiyaku.jp/hinagata/privacy.html
  - https://kiyaku.jp/hinagata/gp.html
- コピペして、マークダウンに整形するところまでは行うが、内容の修正は行わない

# レビュワーに重点的にレビューしてほしいこと
正しくコピペできているか（内容に抜け漏れがないかどうか）は念の為ご確認いただきたいです。

# 補足
特になし

2023-10-14 14:49 UTC, muchoco-dev requested changes
ご対応いただきありがとうございます！

変更したい文言等について、コメントをつけさせていただきました。
無理のない範囲でご対応いただけましたら幸いです:bow:

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +＿＿＿＿＿＿＿＿（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下，「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
`＿＿＿＿＿＿＿＿`→`illubit合同会社`

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +当社は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を，当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，「提携先」といいます。）などから収集することがあります。
`氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの`→`メールアドレスなどの`

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +1. 有料サービスにおいて，ユーザーに利用料金を請求するため
`1. 有料サービスにおいて，ユーザーに利用料金を請求するため`→削除

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +1. 当社は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1 件あたり 1,000 円の手数料を申し受けます。
`当社は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。`→`当社は，本人から個人情報の開示を求められたときは，当社において，本人の個人情報である事が確認できた場合，合理的期間内にこれを開示します。`

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +住所：
`住所：`→`住所： 〒160-0022 東京都新宿区新宿1丁目36番2号 新宿第七葉山ビル3階`

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +社名：
`社名：`→`社名： illubit合同会社`

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +代表取締役：
`代表取締役：`→`代表： 吉岡綾`

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +担当部署：
`担当部署：`→削除

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +E メールアドレス：
`E メールアドレス：`→`E メールアドレス： info@illubit.com`

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +<p style="text-align:right;">
`<p style="text-align:right;">`→削除

2023-10-14 14:49 UTC, muchoco-dev commented on privacy_policy/ja.md
> +<p>
`<p>`→削除

2023-10-14 14:49 UTC, muchoco-dev commented on terms_of_use/ja.md
> +この利用規約（以下，「本規約」といいます。）は，＿＿＿＿＿（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
`＿＿＿＿＿`→`illubit合同会社`

2023-10-14 14:49 UTC, muchoco-dev commented on terms_of_use/ja.md
> +1. ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。
`ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。`→`ユーザは，本サービスを無料で利用することができます。`

2023-10-14 14:49 UTC, muchoco-dev commented on terms_of_use/ja.md
> +1. ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年 14．6％の割合による遅延損害金を支払うものとします。
削除

2023-10-14 14:49 UTC, muchoco-dev commented on terms_of_use/ja.md
> +   1. 料金等の支払債務の不履行があった場合
削除

2023-10-14 14:49 UTC, muchoco-dev commented on terms_of_use/ja.md
> +<p style="text-align:right;">
削除

2023-10-14 14:49 UTC, muchoco-dev commented on terms_of_use/ja.md
> +<p>
削除

2023-10-15 05:03 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +＿＿＿＿＿＿＿＿（以下，「当社」といいます。）は，本ウェブサイト上で提供するサービス（以下，「本サービス」といいます。）における，ユーザーの個人情報の取扱いについて，以下のとおりプライバシーポリシー（以下，「本ポリシー」といいます。）を定めます。
c40e60d047ce4cb1b9ece2f7c7496ae3bbc1ebf5 で対応済みです！

2023-10-15 05:04 UTC, kuniyuki-f commented on terms_of_use/ja.md
> +この利用規約（以下，「本規約」といいます。）は，＿＿＿＿＿（以下，「当社」といいます。）がこのウェブサイト上で提供するサービス（以下，「本サービス」といいます。）の利用条件を定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には，本規約に従って，本サービスをご利用いただきます。
c40e60d047ce4cb1b9ece2f7c7496ae3bbc1ebf5 で対応ずみです！

2023-10-15 05:05 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +当社は，ユーザーが利用登録をする際に氏名，生年月日，住所，電話番号，メールアドレス，銀行口座番号，クレジットカード番号，運転免許証番号などの個人情報をお尋ねすることがあります。また，ユーザーと提携先などとの間でなされたユーザーの個人情報を含む取引記録や決済に関する情報を，当社の提携先（情報提供元，広告主，広告配信先などを含みます。以下，「提携先」といいます。）などから収集することがあります。
03cec8379e5cc374e9f3b6d9c35d4c69d0935ecb で対応済みです！

2023-10-15 05:06 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +1. 有料サービスにおいて，ユーザーに利用料金を請求するため
83953003116914c9c3d84b72c3d441f23c837afd で対応済みです！

2023-10-15 05:08 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +1. 当社は，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。なお，個人情報の開示に際しては，1 件あたり 1,000 円の手数料を申し受けます。
e1098d64df2390afb2b070bed057de67c1edc81c で対応済みです！

2023-10-15 05:11 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +住所：
b20ea3dbc0a9470d92b6d52b9b934df199eb6f4c で対応済みです！

2023-10-15 05:11 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +社名：
b20ea3dbc0a9470d92b6d52b9b934df199eb6f4c で対応済みです！

2023-10-15 05:11 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +代表取締役：
b20ea3dbc0a9470d92b6d52b9b934df199eb6f4c で対応済みです！

2023-10-15 05:11 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +担当部署：
b20ea3dbc0a9470d92b6d52b9b934df199eb6f4c で対応済みです！

2023-10-15 05:11 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +E メールアドレス：
b20ea3dbc0a9470d92b6d52b9b934df199eb6f4c で対応済みです！

2023-10-15 05:11 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +<p style="text-align:right;">
b20ea3dbc0a9470d92b6d52b9b934df199eb6f4c で対応済みです！

2023-10-15 05:11 UTC, kuniyuki-f commented on privacy_policy/ja.md
> +<p>
b20ea3dbc0a9470d92b6d52b9b934df199eb6f4c で対応済みです！

2023-10-15 05:13 UTC, kuniyuki-f commented on terms_of_use/ja.md
> +1. ユーザーは，本サービスの有料部分の対価として，当社が別途定め，本ウェブサイトに表示する利用料金を，当社が指定する方法により支払うものとします。
e538d10aeab490e5fa3c3300d5e4c44ad632b57c で対応済みです！

2023-10-15 05:14 UTC, kuniyuki-f commented on terms_of_use/ja.md
> +1. ユーザーが利用料金の支払を遅滞した場合には，ユーザーは年 14．6％の割合による遅延損害金を支払うものとします。
5118cef409295d7104b9c55dbe70a4763177813d で対応済みです!

2023-10-15 05:16 UTC, kuniyuki-f commented on terms_of_use/ja.md
> +   1. 料金等の支払債務の不履行があった場合
bc526449a8b923abd2690b9ee060fe1469dd50d2 で対応済みです！

2023-10-15 05:17 UTC, kuniyuki-f commented on terms_of_use/ja.md
> +<p style="text-align:right;">
185e47ed9509503a6831acb8cd2665b9c1f8399f で対応済みです！

2023-10-15 05:17 UTC, kuniyuki-f commented on terms_of_use/ja.md
> +<p>
185e47ed9509503a6831acb8cd2665b9c1f8399f で対応済みです！

2023-10-15 05:38 UTC, muchoco-dev approved these changes
ありがとうございます！！
すべての変更リクエスト通りにご変更いただけていたことを確認しました。

2023-10-15 05:39 UTC, merged